videos = {"Santa Claus is Coming to Town":"https://youtu.be/Z1k6Ya7qucQ",
"Oh Little Town of Bethlehem":"https://youtu.be/NqnhL-Yk-fk",
"Last Christmas":"https://youtu.be/VTgJWcQYKWo",
"Amazing Grace":"https://youtu.be/eExUuv1tgHE",
"Away in a Manger":"https://youtu.be/Rvg2uWi4pJ4",
"Frosty the Snowman":"https://youtu.be/49fSRnWncWU",
"Winter Wonderland":"https://youtu.be/wUjU2VjciBk",
"So This is Christmas":"https://youtu.be/iaEYugzFIVQ",
"Jingle Bells Rock":"https://youtu.be/iaEYugzFIVQ",
"The 12 Days of Christmas":"https://youtu.be/2ZS3zmBZxOE",
"Hark the Herald Angels Sing":"https://youtu.be/2ZS3zmBZxOE",
"Joy to the World":"https://youtu.be/NOVCjxLdGQ4",
"Rudolph the Red-Nosed Reindeer":"https://youtu.be/cr0G6muqrEY",
"Have Yourself a Merry Little Christmas":"https://youtu.be/EL46XU7TKJo",
"It's Beginning to Look a Lot Like Christmas":"https://youtu.be/JTAx6V1N7mM",
"The First Noel":"https://youtu.be/ROfWrOKwOqU",
"I'm Dreaming of a White Christmas":"https://youtu.be/dBDu17YaxRM",
"We Wish You a Merry Christmas":"https://youtu.be/uIcDFBy1A9U",
"Oh Come All Ye Faithful":"https://youtu.be/v1tvuaT5iKk",
"Oh Christmas Tree":"https://youtu.be/s-qZ7MOvsWU",
"We Three Kings":"https://youtu.be/BCfk3DAjEJ4",
"Do They Know it's Christmas":"https://youtu.be/azqTIvPu_LQ",
"I Wish it Could be Christmas Every Day":"https://youtu.be/UmSMwhh6tmc",
"Let it Snow":"https://youtu.be/T_XKfAZD_gA",
"Little Drummer Boy":"https://youtu.be/bYsD2mkKHfU",
"Silent Night":"https://youtu.be/RePxsPiNtFk",
"All I Want for Christmas":"https://youtu.be/982M-yDJbOg",
"Walking in the Air":"https://youtu.be/BrdwyVCLlfc",
"Good King Wenceslas":"https://youtu.be/oLrNAE4MiHQ",
"God Rest Ye Merry Gentlemen":"https://youtu.be/FS_2YmVrXys",
"So Here it is Merry Christmas":"https://youtu.be/B9bR5YawWPw",
"On Ilkley Moor":"https://youtu.be/D0m6e_chQik",
"Jingle Bells":"https://youtu.be/WGxuW3SeFhM",
"Deck the Halls":"https://youtu.be/-eCzMi-BVEc"}
